[package]
name = "rlreplayviewer"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boxcars = "0.9.11"
pollster = "0.3.0"
wgpu = "0.19.3"
winit = "0.29.15"

